name: swift_upi
description: "A flutter plugin to do UPI transaction through different apps in Android."
version: 0.0.11
homepage: https://github.com/Rvkt/SwiftUPI.git
environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.rvkt.swift_upi
        pluginClass: SwiftUpiPlugin
      ios:
        pluginClass: SwiftUpiPlugin